# Generated by Django 5.2 on 2025-04-13 05:40

import cloudinary.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Applicants',
            fields=[
                ('applicantId', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('userName', models.CharField(max_length=30)),
                ('userEmail', models.EmailField(max_length=254)),
                ('skills', models.TextField()),
                ('experience', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('companyId', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('companyName', models.CharField(max_length=100)),
                ('companyEmail', models.EmailField(max_length=254)),
                ('companyNumber', models.IntegerField()),
                ('companyWebsite', models.URLField()),
                ('companyAbout', models.TextField()),
                ('companyAddress', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('interviewId', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('skill', models.CharField(max_length=20)),
                ('level', models.CharField(max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='practiceQuestion',
            fields=[
                ('questionId', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('question', models.CharField(max_length=100)),
                ('Type', models.CharField(max_length=100)),
                ('skill', models.CharField(max_length=100)),
                ('level', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='UploadedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', cloudinary.models.CloudinaryField(max_length=255, verbose_name='file')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('userId', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('userFullName', models.CharField(max_length=40)),
                ('userEmail', models.EmailField(max_length=255)),
                ('userPassword', models.CharField(max_length=18)),
                ('userType', models.CharField(default='user', max_length=20)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='codeInterview',
            fields=[
                ('codeInterviewId', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('language', models.CharField(max_length=30)),
                ('time', models.CharField(max_length=50)),
                ('question', models.CharField(max_length=1000)),
                ('code', models.TextField()),
                ('output', models.CharField(max_length=1000)),
                ('feedBack', models.CharField(max_length=1000)),
                ('timeStamp', models.DateTimeField(auto_now_add=True)),
                ('interviewId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.interview')),
            ],
        ),
        migrations.CreateModel(
            name='IntSchedule',
            fields=[
                ('scheduleId', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('intData', models.JSONField()),
                ('applicantId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.applicants')),
            ],
        ),
        migrations.CreateModel(
            name='JobRole',
            fields=[
                ('jobRoleId', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('jobTitle', models.CharField(max_length=50)),
                ('jobDescription', models.TextField()),
                ('jobOpeningAvailable', models.IntegerField()),
                ('jobConstraints', models.JSONField()),
                ('jobExpireTime', models.IntegerField()),
                ('companyId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.company')),
            ],
        ),
        migrations.CreateModel(
            name='mockInterview',
            fields=[
                ('mockInterviewId', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('feedBack', models.JSONField()),
                ('timeStamp', models.DateTimeField(auto_now_add=True)),
                ('interviewId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.interview')),
            ],
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('resumeId', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('cloudUrl', models.URLField(blank=True, null=True)),
                ('skills', models.JSONField()),
                ('experience', models.IntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.userdata')),
            ],
        ),
        migrations.AddField(
            model_name='interview',
            name='userId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.userdata'),
        ),
        migrations.CreateModel(
            name='comments',
            fields=[
                ('commentId', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('userFullName', models.CharField(max_length=50)),
                ('content', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('questionId', models.ForeignKey(max_length=30, on_delete=django.db.models.deletion.CASCADE, to='backend.practicequestion')),
                ('userId', models.ForeignKey(max_length=30, on_delete=django.db.models.deletion.CASCADE, to='backend.userdata')),
            ],
        ),
        migrations.AddField(
            model_name='applicants',
            name='userId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.userdata'),
        ),
    ]
