# Generated by Django 5.1.7 on 2025-03-19 18:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Interview",
            fields=[
                (
                    "interviewId",
                    models.CharField(max_length=30, primary_key=True, serialize=False),
                ),
                ("skill", models.CharField(max_length=20)),
                ("level", models.CharField(max_length=20)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="practiceQuestion",
            fields=[
                (
                    "questionId",
                    models.CharField(max_length=30, primary_key=True, serialize=False),
                ),
                ("question", models.CharField(max_length=100)),
                ("Type", models.CharField(max_length=100)),
                ("skill", models.CharField(max_length=100)),
                ("level", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "userId",
                    models.CharField(max_length=30, primary_key=True, serialize=False),
                ),
                ("userFullName", models.CharField(max_length=40)),
                ("userEmail", models.EmailField(max_length=255)),
                ("userPassword", models.CharField(max_length=18)),
                ("createdAt", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="codeInterview",
            fields=[
                (
                    "codeInterviewId",
                    models.CharField(max_length=30, primary_key=True, serialize=False),
                ),
                ("language", models.CharField(max_length=30)),
                ("time", models.CharField(max_length=50)),
                ("question", models.CharField(max_length=1000)),
                ("code", models.TextField()),
                ("output", models.CharField(max_length=1000)),
                ("feedBack", models.CharField(max_length=1000)),
                ("timeStamp", models.DateTimeField(auto_now_add=True)),
                (
                    "interviewId",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="myapp.interview",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="mockInterview",
            fields=[
                (
                    "mockInterviewId",
                    models.CharField(max_length=30, primary_key=True, serialize=False),
                ),
                ("feedBack", models.JSONField()),
                ("timeStamp", models.DateTimeField(auto_now_add=True)),
                (
                    "interviewId",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="myapp.interview",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Resume",
            fields=[
                (
                    "resumeId",
                    models.CharField(max_length=30, primary_key=True, serialize=False),
                ),
                ("cloudUrl", models.URLField(blank=True, null=True)),
                ("skills", models.JSONField()),
                ("experience", models.IntegerField()),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "userId",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="myapp.user"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="interview",
            name="userId",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="myapp.user"
            ),
        ),
        migrations.CreateModel(
            name="comments",
            fields=[
                (
                    "commentId",
                    models.CharField(max_length=30, primary_key=True, serialize=False),
                ),
                ("userFullName", models.CharField(max_length=50)),
                ("content", models.TextField()),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "questionId",
                    models.ForeignKey(
                        max_length=30,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="myapp.practicequestion",
                    ),
                ),
                (
                    "userId",
                    models.ForeignKey(
                        max_length=30,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="myapp.user",
                    ),
                ),
            ],
        ),
    ]
