# Generated by Django 5.1.7 on 2025-03-20 17:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "companyId",
                    models.CharField(max_length=30, primary_key=True, serialize=False),
                ),
                ("companyName", models.CharField(max_length=100)),
                ("companyEmail", models.EmailField(max_length=254)),
                ("companyNumber", models.IntegerField(max_length=10)),
                ("companyWebsite", models.URLField()),
                ("companyAbout", models.TextField()),
                ("companyAddress", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="Applicants",
            fields=[
                (
                    "applicantId",
                    models.CharField(max_length=30, primary_key=True, serialize=False),
                ),
                ("userName", models.CharField(max_length=30)),
                ("userEmail", models.EmailField(max_length=254)),
                ("skills", models.TextField()),
                ("experience", models.IntegerField()),
                (
                    "userId",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="myapp.user"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="IntSchedule",
            fields=[
                (
                    "scheduleId",
                    models.CharField(max_length=30, primary_key=True, serialize=False),
                ),
                ("intData", models.JSONField()),
                (
                    "applicantId",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="myapp.applicants",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="JobRole",
            fields=[
                (
                    "jobRoleId",
                    models.CharField(max_length=30, primary_key=True, serialize=False),
                ),
                ("jobTitle", models.CharField(max_length=50)),
                ("jobDescription", models.TextField()),
                ("jobOpeningAvailable", models.IntegerField()),
                ("jobConstraints", models.JSONField()),
                ("jobExpireTime", models.IntegerField()),
                (
                    "companyId",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="myapp.company"
                    ),
                ),
            ],
        ),
    ]
