# Generated by Django 5.1.7 on 2025-03-20 17:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0002_company_applicants_intschedule_jobrole"),
    ]

    operations = [
        migrations.AlterField(
            model_name="company",
            name="companyNumber",
            field=models.IntegerField(),
        ),
    ]
