# Generated by Django 5.1.7 on 2025-03-26 18:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0004_user_usertype_alter_applicants_applicantid_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="User",
            new_name="UserData",
        ),
    ]
